"""Train the expense category classifier and write metrics.

    python -m ml.train_classifier

1. Builds the synthetic dataset with merchants held out for the test split.
2. Trains TF-IDF + LogisticRegression and TF-IDF + ComplementNB, evaluates both on unseen merchants.
3. Refits the better one on all merchants and saves ml/artifacts/category_model.joblib.
4. Writes the numbers into ml/metrics.json under "classifier".
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import joblib
from sklearn.metrics import accuracy_score, classification_report, f1_score

from app.categories import CATEGORIES
from ml import dataset
from ml.pipeline import make_cnb, make_logreg

ART = Path(__file__).resolve().parent / "artifacts"
METRICS = Path(__file__).resolve().parent / "metrics.json"
MODEL = ART / "category_model.joblib"


def update_metrics(section: str, payload: dict) -> None:
    data = json.loads(METRICS.read_text()) if METRICS.exists() else {}
    data[section] = payload
    METRICS.write_text(json.dumps(data, indent=2))


def evaluate(model, X_te, y_te) -> dict:
    pred = model.predict(X_te)
    # the hard case: nothing but an unseen merchant name (typical manual entry)
    only = [i for i, x in enumerate(X_te) if x in dataset.known_merchants()]
    return {
        "accuracy": round(accuracy_score(y_te, pred), 4),
        "macro_f1": round(f1_score(y_te, pred, average="macro"), 4),
        "merchant_name_only_accuracy": round(accuracy_score([y_te[i] for i in only], [pred[i] for i in only]), 4),
        "merchant_name_only_n": len(only),
        "per_class_f1": {k: round(v["f1-score"], 3) for k, v in
                          classification_report(y_te, pred, output_dict=True, zero_division=0).items()
                          if k in CATEGORIES},
    }


def train_final(X: list[str], y: list[str], kind: str):
    model = make_logreg() if kind == "logreg" else make_cnb()
    model.fit(X, y)
    return model


def main() -> None:
    X_tr, y_tr, X_te, y_te = dataset.build()
    results = {}
    for name, factory in [("logreg", make_logreg), ("complement_nb", make_cnb)]:
        t = time.perf_counter()
        m = factory().fit(X_tr, y_tr)
        res = evaluate(m, X_te, y_te)
        res["train_seconds"] = round(time.perf_counter() - t, 2)
        results[name] = res
        print(f"{name:14} acc={res['accuracy']:.3f} macroF1={res['macro_f1']:.3f} "
              f"name-only acc={res['merchant_name_only_accuracy']:.3f}")
    best = max(results, key=lambda k: results[k]["macro_f1"])
    X_all, y_all = dataset.build_full()
    final = train_final(X_all, y_all, "logreg" if best == "logreg" else "cnb")
    ART.mkdir(parents=True, exist_ok=True)
    import sklearn
    joblib.dump({"model": final, "kind": best, "trained_on": len(X_all), "feedback_rows": 0,
                 "sklearn": sklearn.__version__}, MODEL, compress=3)
    update_metrics("classifier", {
        "dataset": {"train_samples": len(X_tr), "test_samples": len(X_te),
                    "split": "by merchant - test merchants never appear in training",
                    "note": "synthetic data generated by ml/dataset.py; real-world accuracy will be lower"},
        "models": results,
        "selected": best,
    })
    print(f"saved {MODEL} ({MODEL.stat().st_size / 1024:.0f} KB), selected={best}")


if __name__ == "__main__":
    main()
